version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=TCC
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - app
    restart: always

  api:
    container_name: owl-post
    build:
      context: .
      dockerfile: dockerfile
    image: tcc-api
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/TCC
    - SPRING_DATASOURCE_USER=postgres
    - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  app:
